site_name: TERRA UC1 ROS Bridge Documentation
site_url: https://terra-horizon.github.io/uc1.rosbridge.uth.alpha/

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Bridge Operation: bridge-operation.md
  - Deployment Requirements: deployment-requirements.md
  - Networking: networking.md
  - Walkthrough Demo: example.md
  - Troubleshooting: troubleshooting.md
