site_name: TERRA UC1 - Water Contamination Assessment and Forecasting

site_url: https://terra-horizon.github.io/uc1.forecaster.uth.alpha/
repo_url: https://github.com/terra-horizon/uc1.forecaster.uth.alpha/

nav:
  - Overview: index.md
  - Product Chain 1: example.md
  - System:
      - Architecture: architecture.md
      - Bridge Operation: bridge-operation.md
  - Setup & Monitoring:
      - Deployment: deployment.md
      - Configuration: configuration.md
  - Material:
      - Troubleshooting: troubleshooting.md
  - License: license.md
  - Home: https://terra-horizon.github.io/

theme:
  name: material
  favicon: images/favicon.ico
  logo: images/TERRA_Logo_Header.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - navigation.path
    - navigation.top

extra_css:
  - stylesheets/custom-footer.css
  - stylesheets/mkdocsoad.css
  - stylesheets/header-logo.css

plugins:
  - search
  - mike
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  version:
    provider: mike
    alias: true
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/terra-horizon
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/horizon_terra
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@TERRAHORIZON
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/terra-horizon
